INSERT INTO Marca (Nome) VALUES ('Nike');
INSERT INTO Marca (Nome) VALUES ('Mizuno');
INSERT INTO Marca (Nome) VALUES ('Asics')

INSERT INTO Cor (Nome) VALUES ('Roxo');
INSERT INTO Cor (Nome) VALUES ('Vermelho');
INSERT INTO Cor (Nome) VALUES ('Amarelo');
INSERT INTO Cor (Nome) VALUES ('Preto');
INSERT INTO Cor (Nome) VALUES ('Branco');

INSERT INTO Tamanho (Tam) VALUES ('P');
INSERT INTO Tamanho (Tam) VALUES ('M');
INSERT INTO Tamanho (Tam) VALUES ('G');


INSERT INTO Camiseta (Tipo, IdMarca, IdCor, IdTamanho) VALUES ('Regata', 1, 1, 1);
INSERT INTO Camiseta (Tipo, IdMarca, IdCor, IdTamanho) VALUES ('Blusa', 2, 2, 2);
INSERT INTO Camiseta (Tipo, IdMarca, IdCor, IdTamanho) VALUES ('Sweater', 3, 3, 3);
INSERT INTO Camiseta (Tipo, IdMarca, IdCor, IdTamanho) VALUES ('Top', 2, 4, 1);
INSERT INTO Camiseta (Tipo, IdMarca, IdCor, IdTamanho) VALUES ('Vestido', 1, 5, 2);