INSERT INTO CLIENTE (Nome, Idade) VALUES ('José', 23);
INSERT INTO CLIENTE (Nome, Idade) VALUES ('Tiago', 28);
INSERT INTO CLIENTE (Nome, Idade) VALUES ('Douglas', 56);

INSERT INTO PRODUTOS (Nome, Preco) VALUES ('Caixa de Nugget', 4.80 );
INSERT INTO PRODUTOS (Nome, Preco) VALUES ('Unidade Melão', 5.30);
INSERT INTO PRODUTOS (Nome, Preco) VALUES ('Unidade Melancia', 6.30);

INSERT INTO COMPRA(IdCliente, IdProdutos) VALUES (1,1);
INSERT INTO COMPRA(IdCliente, IdProdutos) VALUES (1,3);
INSERT INTO COMPRA(IdCliente, IdProdutos) VALUES (2,2);
INSERT INTO COMPRA(IdCliente, IdProdutos) VALUES (3,2);