INSERT INTO AUTOR (Nome, Idade) VALUES ('Roberto', 40);
INSERT INTO AUTOR (Nome, Idade) VALUES ('Lucas', 34);
INSERT INTO AUTOR (Nome, Idade) VALUES ('Isabella', 23);

INSERT INTO LIVRO (Nome, Cor) VALUES ('A Tediosa Vida de Berenice', 'Azul');
INSERT INTO LIVRO (Nome, Cor) VALUES ('Claramente desamor', 'Vermelho');
INSERT INTO LIVRO (Nome, Cor) VALUES ('Finalmente', 'Roxo');

INSERT INTO ESCRITA (IdAutor, IdLivro) VALUES (1,1);
INSERT INTO ESCRITA (IdAutor, IdLivro) VALUES (1,3);
INSERT INTO ESCRITA (IdAutor, IdLivro) VALUES (2,2);
INSERT INTO ESCRITA (IdAutor, IdLivro) VALUES (3,2);